global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['127.0.0.1:9093']

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
          - admin-node:9100
          - web-node:9100
          - db-node:9100
          - log-node:9100
